#!/usr/bin/env python3
"""Create source-registry sub-hubs for currently uningested raw candidates.

The script reads the report generated by ``find-uningested-raw.py --report``,
groups candidate raw paths by stable source clusters, writes small summary pages
under ``wiki/summaries/``, and refreshes an auto-managed section in the summaries
index. It does not copy raw contents into the wiki; it registers source paths so
raw-to-wiki coverage can be tracked without making oversized hub pages.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import re
import unicodedata
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / "outputs" / "reports" / f"uningested-raw-{dt.date.today():%Y%m%d}.md"
SUMMARIES = ROOT / "wiki" / "summaries"
INDEX = SUMMARIES / "_index.md"

MAX_SOURCES_PER_PAGE = 80
BEGIN = "<!-- AUTO:REMAINING-RAW-SUBHUBS:BEGIN -->"
END = "<!-- AUTO:REMAINING-RAW-SUBHUBS:END -->"


def normalize_text(value: str) -> str:
    return unicodedata.normalize("NFC", value)


def source_path(path: str) -> str:
    return normalize_text(path.replace("\\", "/"))


def slugify(value: str, max_len: int = 90) -> str:
    value = normalize_text(value).lower()
    value = re.sub(r"[^0-9a-z가-힣]+", "-", value).strip("-")
    value = re.sub(r"-+", "-", value)
    return value[:max_len].strip("-") or "raw"


def parse_report(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    candidates: list[str] = []
    row_re = re.compile(r"^\|\s*\d+\s*\|\s*-?\d+\s*\|\s*[^|]+\|\s*`(raw/[^`]+)`", re.M)
    for match in row_re.finditer(text):
        candidates.append(source_path(match.group(1).replace(r"\|", "|")))
    return sorted(set(candidates))


def course_for_mslearn(path: str) -> str | None:
    match = re.match(r"raw/articles/mslearn/([^/]+)/", path)
    return match.group(1) if match else None


def group_key(path: str) -> tuple[str, str, str, str]:
    parts = path.split("/")
    if len(parts) < 3:
        return ("raw", "Raw 미분류", "[type/summary, type/source-registry]", "")

    if path.startswith("raw/articles/mslearn/"):
        course = course_for_mslearn(path) or "unknown"
        return (
            f"articles/mslearn/{course}",
            f"MS Learn 미수집 Conflict 자료 — {course.upper()}",
            "[type/summary, type/source-registry, type/mslearn]",
            f"[[mslearn-{course}]]",
        )

    if path.startswith("raw/articles/"):
        return (
            f"articles/{parts[2]}",
            f"Articles 미수집 자료 — {parts[2]}",
            "[type/summary, type/source-registry]",
            "",
        )

    if path.startswith("raw/obsidian/"):
        category = parts[2] if len(parts) > 2 else "root"
        return (
            f"obsidian/{category}",
            f"Obsidian 원본 미수집 자료 — {category}",
            "[type/summary, type/source-registry, topic/obsidian]",
            "[[owen-knowledge-base]]",
        )

    if path.startswith("raw/extracted/working/"):
        cluster = parts[3] if len(parts) > 3 else "working"
        return (
            f"extracted/working/{cluster}",
            f"Working 추출물 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, type/working]",
            "",
        )

    if path.startswith("raw/extracted/microsoft-documents/"):
        cluster = parts[3] if len(parts) > 3 else "microsoft-documents"
        return (
            f"extracted/microsoft-documents/{cluster}",
            f"MS Korea Microsoft Documents 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, prod/microsoft-security]",
            "[[ms-korea-microsoft-documents-hub]]",
        )

    if path.startswith("raw/extracted/onsite-reports/"):
        cluster = parts[3] if len(parts) > 3 else "onsite-reports"
        return (
            f"extracted/onsite-reports/{cluster}",
            f"Onsite Reports 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, type/customer-engagement]",
            "[[onsite-reports-content-hub]]",
        )

    if path.startswith("raw/extracted/readiness-archives/"):
        cluster = parts[3] if len(parts) > 3 else "readiness-archives"
        return (
            f"extracted/readiness-archives/{cluster}",
            f"Readiness Archives 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, type/readiness]",
            "[[readiness-archives-hub]]",
        )

    if path.startswith("raw/extracted/fy26-readiness/"):
        cluster = parts[3] if len(parts) > 3 else "fy26-readiness"
        return (
            f"extracted/fy26-readiness/{cluster}",
            f"FY26 Readiness 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, series/fy26-readiness]",
            "[[fy26-readiness-extras-hub]]",
        )

    if path.startswith("raw/extracted/articles/"):
        cluster = parts[3] if len(parts) > 3 else "articles"
        return (
            f"extracted/articles/{cluster}",
            f"Extracted Articles 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry]",
            "",
        )

    if path.startswith("raw/security-microsoft-documents/"):
        cluster = parts[2] if len(parts) > 2 else "security-microsoft-documents"
        return (
            f"security-microsoft-documents/{cluster}",
            f"Security Microsoft Documents symlink 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, prod/microsoft-security]",
            "",
        )

    if path.startswith("raw/security-onsite-reports/"):
        cluster = parts[2] if len(parts) > 2 else "security-onsite-reports"
        return (
            f"security-onsite-reports/{cluster}",
            f"Security Onsite Reports symlink 미수집 자료 — {cluster}",
            "[type/summary, type/source-registry, type/customer-engagement]",
            "",
        )

    top = parts[1]
    cluster = parts[2] if len(parts) > 2 else top
    return (
        f"{top}/{cluster}",
        f"Raw 미수집 자료 — {top}/{cluster}",
        "[type/summary, type/source-registry]",
        "",
    )


def chunks(items: list[str], size: int) -> list[list[str]]:
    return [items[index : index + size] for index in range(0, len(items), size)]


def page_name(key: str, part: int, total_parts: int) -> str:
    digest = hashlib.sha1(key.encode("utf-8")).hexdigest()[:8]
    suffix = f"-part-{part}" if total_parts > 1 else ""
    return f"remaining-raw-{slugify(key)}{suffix}-{digest}.md"


def render_page(title: str, tags: str, key: str, paths: list[str], parent_link: str, part: int, total_parts: int) -> str:
    today = dt.date.today().isoformat()
    part_label = f" (part {part}/{total_parts})" if total_parts > 1 else ""
    sources = "\n".join(f"  - '{path.replace(chr(39), chr(39) + chr(39))}'" for path in paths)
    related_links = ["[[remaining-raw-source-registry-hub]]"]
    if parent_link and parent_link not in related_links:
        related_links.append(parent_link)
    related = "\n".join(f"- {link}" for link in related_links)
    parent_section = f"\n## 관련 허브\n\n{related}\n"
    return f'''---
title: "{title}{part_label}"
type: summary
tags: {tags}
sources:
{sources}
created: {today}
updated: {today}
confidence: 0.55
last_confirmed: {today}
---

# {title}{part_label}

`raw/{key}/` 계열에서 아직 wiki sources로 참조되지 않던 원본을 자동 수집한 source registry sub-hub다. 이 페이지는 원문 내용을 복사하지 않고 파일 경로만 등록하여 raw coverage 추적과 후속 큐레이션의 기준점으로 사용한다.
{parent_section}
## 수집 범위

- 등록 sources: {len(paths)}개
- 생성 방식: `scripts/absorb-uningested-subhubs.py`
- 후속 작업: 가치 높은 개별 파일은 별도 summary로 승격하고, 이 페이지에서 해당 summary를 링크한다.

## 큐레이션 메모

- 이 페이지는 자동 source registry이며 원문 내용 복사 없이 sources coverage를 보장한다.
- 후속 큐레이션 시 중복, 구버전, 고객사별 파생본 여부를 검토한다.
'''


def refresh_index(entries: list[tuple[str, str, int]]) -> None:
    text = INDEX.read_text(encoding="utf-8")
    total_sources = sum(count for _, _, count in entries)
    lines = [
        BEGIN,
        "## 2026-04-25 신규 (미수집 raw 자동 sub-hub 수집)",
        f"- 총 {len(entries)}개 sub-hub / {total_sources}개 raw source path 등록",
    ]
    for stem, title, count in entries:
        lines.append(f"- [[{stem}]] — {title} ({count} sources)")
    lines.append(END)
    block = "\n".join(lines) + "\n"

    if BEGIN in text and END in text:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)
        text = pattern.sub(block, text)
    else:
        text = text.rstrip() + "\n\n" + block
    text = re.sub(r"updated: \d{4}-\d{2}-\d{2}", f"updated: {dt.date.today().isoformat()}", text, count=1)
    INDEX.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path, default=REPORT)
    parser.add_argument("--chunk-size", type=int, default=MAX_SOURCES_PER_PAGE)
    args = parser.parse_args()

    if not args.report.exists():
        raise SystemExit(f"Report not found: {args.report}")

    candidates = parse_report(args.report)
    grouped: dict[str, dict[str, object]] = {}
    paths_by_key: defaultdict[str, list[str]] = defaultdict(list)
    for path in candidates:
        key, title, tags, parent = group_key(path)
        paths_by_key[key].append(path)
        grouped[key] = {"title": title, "tags": tags, "parent": parent}

    entries: list[tuple[str, str, int]] = []
    written = 0
    for key, paths in sorted(paths_by_key.items()):
        meta = grouped[key]
        chunked = chunks(sorted(set(paths)), args.chunk_size)
        for index, chunk in enumerate(chunked, 1):
            filename = page_name(key, index, len(chunked))
            title = str(meta["title"])
            page = render_page(
                title=title,
                tags=str(meta["tags"]),
                key=key,
                paths=chunk,
                parent_link=str(meta["parent"]),
                part=index,
                total_parts=len(chunked),
            )
            (SUMMARIES / filename).write_text(page, encoding="utf-8")
            entries.append(((SUMMARIES / filename).stem, title, len(chunk)))
            written += 1

    refresh_index(entries)
    print(f"Candidates parsed: {len(candidates)}")
    print(f"Groups: {len(paths_by_key)}")
    print(f"Sub-hubs written: {written}")
    print(f"Sources registered: {sum(count for _, _, count in entries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())