"""Automate template/wiki release validation, commit, tag, push, and GitHub Release creation."""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
VERSION_PATTERN = re.compile(r'^\d+\.\d+$')

STAGE_PATHS = [
    '.github/workflows/wiki-lint.yml',
    'AGENTS.md',
    'CHANGELOG.md',
    'README.md',
    'SETUP-GUIDE.md',
    'index.md',
    'starter-files',
    'templates',
    'ontology-templates',
    'scripts',
    'wiki',
    'graphify-out',
    'outputs/wiki-ops',
]


def python_files():
    return sorted(
        str(path.relative_to(ROOT))
        for path in (ROOT / 'scripts').glob('*.py')
    )


def validation_commands():
    commands = [[sys.executable, '-m', 'py_compile', *python_files()]]
    if (ROOT / 'wiki' / 'ontology').exists():
        commands.extend([
            [sys.executable, 'scripts/check-ontology.py'],
            [sys.executable, 'scripts/wiki-quality-gates.py'],
            [sys.executable, 'scripts/check-graph-hygiene.py'],
            [sys.executable, 'scripts/check-related-to-budget.py'],
        ])
    commands.append(['git', 'diff', '--check'])
    return commands


def command_for_display(command):
    display = []
    skip_next = False
    for part in command:
        if skip_next:
            skip_next = False
            continue
        display.append(part)
        if part == '--notes':
            display.append('<release notes>')
            skip_next = True
    return ' '.join(display)


def print_command(command):
    text = '+ ' + command_for_display(command)
    encoding = sys.stdout.encoding or 'utf-8'
    safe_text = text.encode(encoding, errors='backslashreplace').decode(encoding, errors='replace')
    print(safe_text)


def run(command, dry_run=False):
    print_command(command)
    if dry_run:
        return
    env = os.environ.copy()
    env['PYTHONDONTWRITEBYTECODE'] = '1'
    subprocess.run(command, cwd=ROOT, check=True, env=env)


def main():
    parser = argparse.ArgumentParser(description='Release wiki repository.')
    parser.add_argument('version', help='Bare numeric release version, e.g. 1.17')
    parser.add_argument('--message', default='', help='Commit/tag message')
    parser.add_argument('--push', action='store_true', help='Push main and tag')
    parser.add_argument('--github-release', action='store_true', help='Create GitHub Release with gh')
    parser.add_argument('--dry-run', action='store_true', help='Print commands only')
    args = parser.parse_args()
    version = args.version.strip()
    if not VERSION_PATTERN.fullmatch(version):
        parser.error('release version must be a bare major.minor number, e.g. 1.17')
    message = args.message or version
    for command in validation_commands():
        run(command, args.dry_run)
    if (ROOT / 'outputs' / 'wiki-ops' / 'repo-metrics.json').exists():
        run([sys.executable, 'scripts/update-metrics-snippets.py'], args.dry_run)
    stage_paths = [path for path in STAGE_PATHS if (ROOT / path).exists()]
    run(['git', 'add', *stage_paths], args.dry_run)
    run(['git', 'commit', '-m', message], args.dry_run)
    run(['git', 'tag', '-a', version, '-m', version], args.dry_run)
    if args.push:
        run(['git', 'push', 'origin', 'main'], args.dry_run)
        run(['git', 'push', 'origin', version], args.dry_run)
    if args.github_release:
        notes = changelog_notes(version)
        run(['gh', 'release', 'create', version, '--title', version, '--notes', notes], args.dry_run)


def changelog_notes(version):
    changelog = ROOT / 'CHANGELOG.md'
    if not changelog.exists():
        return 'Generated by scripts/release-wiki.py'
    text = changelog.read_text(encoding='utf-8')
    headings = [version, f'{version}.0']
    start = -1
    marker = ''
    for heading in headings:
        marker = f'## [{heading}]'
        start = text.find(marker)
        if start >= 0:
            break
    if start < 0:
        return 'Generated by scripts/release-wiki.py'
    next_heading = text.find('\n## [', start + len(marker))
    section = text[start: next_heading if next_heading >= 0 else len(text)].strip()
    return section


if __name__ == '__main__':
    main()